version: "3"
services:
  application:
    image: spring-boot-mysql-app
    ports: 
    - "9090:9090"
    networks:
    - springboot-db-net
    depends_on: 
    - mysqldb
    volumes:
    - /data/springboot-app
  mysqldb:
    image: mysql
    networks:
    - springboot-db-net
    environment:
    - MYSQL_ROOT_PASSWORD=orcl
    - MYSQL_DATABASE=mydb
    volumes:
    - /data/mysql
networks:
  springboot-db-net: