spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: orcl
    url: jdbc:mysql://localhost:3306/mydb
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9090
